version: '3'

services:
  api:
    container_name: notebook
    restart: always
    build: .
    ports:
      - '5000:3000'
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo_database
    image: mongo
    ports:
      - '27018:27012'
    logging:
      driver: none
